feat: add tip 9 about sensitive data
ksylor/ohshitgit pull request #52
Opened 2020-08-16 05:30 UTC by tim-hub

sometimes, when commit .env, api keys, private email, or even worse, credit card!!!!

- ref
https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

2020-08-16 05:32 UTC, tim-hub commented
preview looks fine.
https://deploy-preview-52--ohshitgit.netlify.app/en/swears/index.html

2020-09-07 08:08 UTC, lwojcik commented
Note to self: add PL translation if this gets merged.

2020-11-21 19:29 UTC, thetayloredman requested changes

2020-11-21 19:29 UTC, thetayloredman commented on en/noswears/tips/09-remove-sensitive-data.md
> +title: Dangit, I commit some sensitive data in!
```suggestion
title: Dangit, I commited some sensitive data in!
```

`commit` seems like the improper tense here.

2020-11-21 19:29 UTC, thetayloredman commented on en/swears/tips/09-remove-sensitive-data.md
> +title: Oh shit, I commit some sensitive data in!
```suggestion
title: Oh shit, I commited some sensitive data in!
```

`commit` seems like the improper tense here.

2020-11-21 19:29 UTC, thetayloredman commented on en/swears/tips/09-remove-sensitive-data.md
> +Trust me, if it was credit card, it would be too late to do this.
```suggestion
Trust me, if it was credit card details, it would be too late to do this.
```

2020-11-21 19:29 UTC, thetayloredman commented on en/noswears/tips/09-remove-sensitive-data.md
> +Trust me, if it was credit card, it would be too late to do this.
```suggestion
Trust me, if it was credit card details, it would be too late to do this.
```

2020-11-21 20:19 UTC, cybear commented
I'll be honest about this PR. I think it's good to have a tip about private data, however this is not detailed enough. For instance it doesn't explain that it's a much better problem if you only have committed the sensitive data to your local repo and never pushed it. It doesn't explain anything about what kind of sensitive data we're talking about. It doesn't tell you what's "too late" - that someone else could be using the credit card in the example.
Finally it doesn't have a humorous tone and no curses.

This is just my personal opinion, please take it with a pinch of salt. But I think it's hard to write a tip in the same voice as @ksylor :)

2021-02-27 15:02 UTC, ksylor commented
So, apologies for leaving this hanging for so long, I've been thinking about adding this suggestion and debating with myself ever since you made the suggestion! I've decided that while this is a really valuable tip, it doesn't really fit with the intent of the site. The idea behind ohshitgit is that it should be a quick reference for someone who made a mistake and needs to figure out how to fix it *in the moment*, and I try to make the commands as simple and non-destructive to git history as possible so that folks can get out of their immediate problem and move on. 

Unfortunately, I think a tip like this that involves potentially re-writing whole swaths of the history of a git repo is a super complex topic that just doesn't fit into the "Oh Shit" format. I'd want to devote an entire blog post to discussing the pros and cons and tradeoffs involved, and there's a ton of complexity around making this kind of a change at a job where the repo is shared with lots of folks and is the basis for a CI/CD pipeline, etc. 

Thank you for your suggestion, I do appreciate it and the time you put into making a PR! In the future I might revisit a longer-format blog-type addition to the main site where bigger issues like this would be on the table.

2021-02-27 15:02 UTC, closed without merging