Add hindi translations
ksylor/ohshitgit pull request #61
Opened 2020-09-14 11:56 UTC by aryansarkar13

Previous PR issues fixed.
Happy National Hindi Day!

2020-10-25 13:20 UTC, ksylor requested changes
This looks great, thanks so much Aryan! 

I mentioned this in a comment, but I'd prefer that we use the two-letter code `hi` instead of `hin` so that server-side language detection that uses the two-letter ISO-639 codes will work, so please update the PR to use the two-digit code, thanks!

2020-10-25 13:20 UTC, ksylor commented on _redirects
> +# hindi swears
Missed this copy/paste redirect, replace the `fr` with `hi`

2020-10-25 13:20 UTC, ksylor commented on .eleventy.js
> +  //Hindi language version
Let's use the ISO-639 two-letter code of `hi` so that server-side language detection can properly redirect to the correct language https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

2020-10-28 09:43 UTC, aryansarkar13 commented on _redirects
> +# hindi swears
Oops, corrected it.

2021-02-27 13:51 UTC, ksylor approved these changes
WOW Okay sorry that I left this hanging around for so long! COVID has really done a number on my free time! Anyways, this looks great, and I'll take care of merging it now. 

THANK YOU!!!!!

2021-02-27 13:54 UTC, merged