Czech text correction
ksylor/ohshitgit pull request #88
Opened 2021-01-14 12:01 UTC by kolaron

Pull request with few text corrections, which I spotted. There was few small changes, but it's my first pull request, so I hope it's not useless. 👍

2021-01-17 14:29 UTC, adaamz requested changes

2021-01-17 14:29 UTC, adaamz commented on cs/noswears/partials/intro.njk
> +<p>Git je složitý: něco rozbít je jednoduché, ale přijít na to, jak z toho ven někdy téměř nemožné. Hledat něco v dokumentaci Gitu jde těžko, <em>pokud tedy už nevíš název té věci, kterou hledáš</em>
```suggestion
<p>Git je složitý: něco rozbít je jednoduché, ale přijít na to, jak z toho ven je někdy téměř nemožné. Hledat něco v dokumentaci Gitu jde těžko, <em>pokud tedy už nevíš název té věci, kterou hledáš</em>. </p>
```

2021-01-17 14:29 UTC, adaamz commented on cs/swears/partials/intro.njk
> +<p>Git je složitý: něco posrat je jednoduché, ale přijít na to, jak z toho ven někdy téměř nemožné. Hledat něco v dokumentaci Gitu jde těžko, <em>pokud tedy už nevíš název té věci, kterou hledáš</em>
```suggestion
<p>Git je složitý: něco posrat je jednoduché, ale přijít na to, jak z toho ven je někdy téměř nemožné. Hledat něco v dokumentaci Gitu jde těžko, <em>pokud tedy už nevíš název té věci, kterou hledáš</em>. </p>
```

2021-02-27 14:50 UTC, ksylor commented
Thanks so much for this @kolaron

I'm not sure if you think that the additional changes @adaamz suggested should be added to your PR? It would be great to figure that out before I merge this in. Let me know, thanks!

2021-03-01 09:51 UTC, kolaron reviewed
You can merge it, all additional changes by @adaamz are OK.

2021-03-01 13:54 UTC, merged

2021-03-01 13:54 UTC, ksylor commented
Thanks so much @kolaron !!